### ISSUE TITLE
Account menu: Copy Wallet Address doesn't work 

### ISSUE THREAD

**Issue by idaroobear** [AraBlocks/ara-file-manager#586]
Description: 
Clicking the Wallet Address in the account menu doesn't work. User has no way of copying the address without manually typing it out. 

Severity: 
High 

Steps to Reproduce: 
1. Log in to FM
2. Click hamburger menu
3. Click Account
4. Click the string under Wallet Address
5. Paste the Wallet Address in notes 

Expected Result:
1. "Wallet Address copied" notification 
2. ID successfully pastes in notes

Actual Result: 
1. Notification appears but Wallet Address didn't copy

**Comment by zootella** [comment]
@mahjiang fixed in 0.12.7!
