### ISSUE TITLE
Account menu: Copy ARA ID doesn't work

### ISSUE THREAD

**Issue by idaroobear** [AraBlocks/ara-file-manager#587]
Description: 
Clicking the Wallet ID in the account menu doesn't work. User has no way of copying the ID without manually typing it out. 

Severity: 
High 

Steps to Reproduce: 
1. Log in to FM
2. Click hamburger menu
3. Click Account
4. Click the string under ARA ID 
5. Paste the ARA ID in notes 

Expected Result:
1. "ARA ID copied" notification appears
2. ID successfully pastes in notes

Actual Result: 
1. Notification appears, but ARA ID isn't copied

**Comment by zootella** [comment]
@mahjiang fixed in 0.12.7!
